# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.radi.trace.com:
  peer1.radi.trace.com:
  peer2.radi.trace.com:

networks:
  trace:

services:

  orderer.radi.trace.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.radi.trace.com
    container_name: orderer.radi.trace.com
    networks:
      - trace

  peer1.radi.trace.com:
    container_name: peer1.radi.trace.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.radi.trace.com
    networks:
      - trace
    depends_on:
      - couchdb0

  peer2.radi.trace.com:
    container_name: peer2.radi.trace.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer2.radi.trace.com
    networks:
      - trace
    depends_on:
      - couchdb1

  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true #whether binds with a console to communicate with users
    stdin_open: true #standard in open to external
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer1.radi.trace.com:7051
      - CORE_PEER_LOCALMSPID=RadiMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/radi.trace.com/peers/peer1.radi.trace.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/radi.trace.com/peers/peer1.radi.trace.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/radi.trace.com/peers/peer1.radi.trace.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/radi.trace.com/users/Admin@radi.trace.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crymaterials:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifitial:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.radi.trace.com
      - peer1.radi.trace.com
      - peer2.radi.trace.com
    networks:
      - trace

  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      - trace

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "6984:5984"
    networks:
      - trace

