// Code generated by Kitex v0.2.0. DO NOT EDIT.

package ccoperation

import (
	"context"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	ccapi "radi/rpc/kitex_gen/ccAPI"
)

func serviceInfo() *kitex.ServiceInfo {
	return cCOperationServiceInfo
}

var cCOperationServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "CCOperation"
	handlerType := (*ccapi.CCOperation)(nil)
	methods := map[string]kitex.MethodInfo{
		"CCInstall": kitex.NewMethodInfo(cCInstallHandler, newCCOperationCCInstallArgs, newCCOperationCCInstallResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "ccapi",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.2.0",
		Extra:           extra,
	}
	return svcInfo
}

func cCInstallHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*ccapi.CCOperationCCInstallArgs)
	realResult := result.(*ccapi.CCOperationCCInstallResult)
	success, err := handler.(ccapi.CCOperation).CCInstall(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newCCOperationCCInstallArgs() interface{} {
	return ccapi.NewCCOperationCCInstallArgs()
}

func newCCOperationCCInstallResult() interface{} {
	return ccapi.NewCCOperationCCInstallResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) CCInstall(ctx context.Context, req *ccapi.CCInstallReq) (r *ccapi.CCInstallResp, err error) {
	var _args ccapi.CCOperationCCInstallArgs
	_args.Req = req
	var _result ccapi.CCOperationCCInstallResult
	if err = p.c.Call(ctx, "CCInstall", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
