// Code generated by Kitex v0.2.0. DO NOT EDIT.

package ccoperation

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	ccapi "radi/rpc/kitex_gen/ccAPI"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CCInstall(ctx context.Context, req *ccapi.CCInstallReq, callOptions ...callopt.Option) (r *ccapi.CCInstallResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCCOperationClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCCOperationClient struct {
	*kClient
}

func (p *kCCOperationClient) CCInstall(ctx context.Context, req *ccapi.CCInstallReq, callOptions ...callopt.Option) (r *ccapi.CCInstallResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CCInstall(ctx, req)
}
