// Code generated by Kitex v0.2.0. DO NOT EDIT.
package ccoperation

import (
	"github.com/cloudwego/kitex/server"
	ccapi "radi/rpc/kitex_gen/ccAPI"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler ccapi.CCOperation, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
